name: Deploy to Cloud Run

on:
  push:
    branches:
      - qa

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: qa

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Debug
        run: |
          pwd
          ls -la
          ls -la app
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}"

      - name: Set Variables
        run: |
          echo "IMAGE_NAME=demo-app-qa" >> $GITHUB_ENV
          echo "SERVICE_NAME=demo-app-qa" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -t test-image ./app

      - name: Tag Image
        run: docker tag test-image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/app-repo/demo-app-qa:${{ github.sha }}

      - name: Push Image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/app-repo/demo-app-qa:${{ github.sha }}

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy demo-app-qa \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/app-repo/demo-app-qa:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
